name: Fetch YacineTV Channels By Category

on:
  schedule:
    - cron: '0 4 * * *'  # Run daily at 4 AM UTC
  workflow_dispatch:
    inputs:
      category_id:
        description: 'Category ID to fetch channels for'
        required: true
        default: '86'

jobs:
  fetch-category-channels:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run category channels fetcher
        run: |
          CATEGORY_ID=${{ github.event_name == 'workflow_dispatch' && github.event.inputs.category_id || '86' }}
          python get_channels_by_category.py $CATEGORY_ID ytv_channels_cat${CATEGORY_ID}_latest.json
        
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: ytv-category-channels
          path: ytv_channels_cat*_latest.json
          retention-days: 7 