name: Fetch All Data

on:
  workflow_dispatch:  # Allows you to trigger manually from GitHub UI or API
    inputs:
      channel_id:
        description: 'Channel ID to fetch'
        required: false
        default: '4'
      category_id:
        description: 'Category ID to fetch channels for'
        required: false
        default: '86'

jobs:
  run-fetch-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Run All Data Scripts
        run: |
          python get_categories.py
          python get_channel_data.py ${{ github.event.inputs.channel_id || '4' }}
          python get_channels_by_category.py ${{ github.event.inputs.category_id || '86' }} 