name: Fetch Channel Data

on:
  workflow_dispatch:  # Allows you to trigger manually from GitHub UI or API
    inputs:
      channel_id:
        description: 'Channel ID to fetch'
        required: true
        default: '4'

jobs:
  run-fetch-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Run Channel Data Script
        run: |
          python get_channel_data.py ${{ github.event.inputs.channel_id }} 