name: Fetch Channels By Category

on:
  workflow_dispatch:  # Allows you to trigger manually from GitHub UI or API
    inputs:
      category_id:
        description: 'Category ID to fetch channels for'
        required: true
        default: '86'

jobs:
  run-fetch-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Run Category Channels Script
        run: |
          python get_channels_by_category.py ${{ github.event.inputs.category_id }} 