name: Fetch YacineTV Channel Data

on:
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2 AM UTC
  workflow_dispatch:
    inputs:
      channel_id:
        description: 'Channel ID to fetch'
        required: true
        default: '4'

jobs:
  fetch-channel:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run channel data fetcher
        run: |
          CHANNEL_ID=${{ github.event_name == 'workflow_dispatch' && github.event.inputs.channel_id || '4' }}
          python get_channel_data.py $CHANNEL_ID ytv_channel_${CHANNEL_ID}_latest.json
        
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: ytv-channel-data
          path: ytv_channel_*_latest.json
          retention-days: 7 