name: Fetch Categories Data

on:
  workflow_dispatch:  # Allows you to trigger manually from GitHub UI or API

jobs:
  run-fetch-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Run Categories Data Script
        run: |
          python get_categories.py